backend:
  name: github
  repo: rudah-amaral/my-hugo-cms-poc # Path to your GitHub repository
  branch: main

media_folder: "static/decap-images"

collections:
  - name: 'posts' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Posts' # Used in the UI
    label_singular: 'Post' # Used in the UI, ie: "New Post"
    description: >
      Crie um post básico no site
    folder: 'content/'
    create: true # Allow users to create new documents in this collection

    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DDTHH:mm:ssZ',
          default: '{{now}}',
        }
      - { label: 'Tags', name: 'tags', widget: 'list', required: true}
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
#
#
#
# +++
# date = '2025-07-28T17:24:34-03:00'
#         2025-07-28T17:55:00-03:00
# title = 'About'
# tags = ['my custom tag']
# +++
